services:
  job_posting.event_listener.add_job_content_config_listener:
    class: Dreibein\JobpostingBundle\EventListener\DataContainer\AddJobContentConfigListener

  job_posting.event_listener.data_container.job_listener:
    class: Dreibein\JobpostingBundle\EventListener\DataContainer\JobListener
    public: true
    arguments:
      - '@contao.image.image_sizes'
      - '@job_posting.job.url_generator'

  job_posting.event_listener.data_container.job_category_listener:
    class: Dreibein\JobpostingBundle\EventListener\DataContainer\JobCategoryListener
    public: true

  job_posting.event_listener.data_container.module_listener:
    class: Dreibein\JobpostingBundle\EventListener\DataContainer\ModuleListener
    public: true

  job_posting.event_listener.get_searchable_pages_listener:
    class: Dreibein\JobpostingBundle\EventListener\GetSearchablePagesListener

  job_posting.event_listener.insert_tags_listener:
    class: Dreibein\JobpostingBundle\EventListener\InsertTagsListener
    arguments:
      - '@contao.framework'
      - '@job_posting.job.url_generator'
