services:
  Dreibein\JobpostingBundle\EventListener\DataContainer\AddJobContentConfigListener:
    class: Dreibein\JobpostingBundle\EventListener\DataContainer\AddJobContentConfigListener

  Dreibein\JobpostingBundle\EventListener\DataContainer\JobListener:
    class: Dreibein\JobpostingBundle\EventListener\DataContainer\JobListener
    public: true
    arguments:
      - '@contao.image.image_sizes'
      - '@Dreibein\JobpostingBundle\Job\UrlGenerator'
      - '@Dreibein\JobpostingBundle\Job\AliasGenerator'
      - '@translator'

  Dreibein\JobpostingBundle\EventListener\DataContainer\JobCategoryListener:
    class: Dreibein\JobpostingBundle\EventListener\DataContainer\JobCategoryListener
    public: true
    arguments:
      - '@Dreibein\JobpostingBundle\Job\AliasGenerator'

  Dreibein\JobpostingBundle\EventListener\DataContainer\ModuleListener:
    class: Dreibein\JobpostingBundle\EventListener\DataContainer\ModuleListener
    public: true

  Dreibein\JobpostingBundle\EventListener\GetSearchablePagesListener:
    class: Dreibein\JobpostingBundle\EventListener\GetSearchablePagesListener

  Dreibein\JobpostingBundle\EventListener\InsertTagsListener:
    class: Dreibein\JobpostingBundle\EventListener\InsertTagsListener
    arguments:
      - '@contao.framework'
      - '@Dreibein\JobpostingBundle\Job\UrlGenerator'
