services:
  Dreibein\JobpostingBundle\Controller\ContentElement\JobDisplayController:
    class: Dreibein\JobpostingBundle\Controller\ContentElement\JobDisplayController
    arguments:
      - '@Dreibein\JobpostingBundle\Job\JobParser'
      - '@Dreibein\JobpostingBundle\Job\JsonParser'

  Dreibein\JobpostingBundle\Controller\FrontendModule\JobListController:
    class: Dreibein\JobpostingBundle\Controller\FrontendModule\JobListController
    arguments:
      - '@Dreibein\JobpostingBundle\Job\JobParser'
    tags:
      - { name: contao.frontend_module, category: jobs, type: job_list }

  Dreibein\JobpostingBundle\Controller\FrontendModule\JobReaderController:
    class: Dreibein\JobpostingBundle\Controller\FrontendModule\JobReaderController
    arguments:
      - '@Dreibein\JobpostingBundle\Job\JobParser'
      - '@Dreibein\JobpostingBundle\Job\JsonParser'
    tags:
      - { name: contao.frontend_module, category: jobs, type: job_reader }

  Dreibein\JobpostingBundle\Job\AliasGenerator:
    class: Dreibein\JobpostingBundle\Job\AliasGenerator
    arguments:
      - '@contao.slug'

  Dreibein\JobpostingBundle\Job\JobParser:
    class: Dreibein\JobpostingBundle\Job\JobParser
    arguments:
      - '@Dreibein\JobpostingBundle\Job\UrlGenerator'
      - '%kernel.project_dir%'

  Dreibein\JobpostingBundle\Job\JsonParser:
    class: Dreibein\JobpostingBundle\Job\JsonParser

  Dreibein\JobpostingBundle\Job\UrlGenerator:
    class: Dreibein\JobpostingBundle\Job\UrlGenerator
    public: true
    arguments:
      - '@request_stack'

  Dreibein\JobpostingBundle\Picker\JobPickerProvider:
    class: Dreibein\JobpostingBundle\Picker\JobPickerProvider
    arguments:
      - '@knp_menu.factory'
      - '@router'
